---
title: "General Conference Quotes"
author: "Kameron York"
date: "2023-10-15"
output:
  html_document:
    includes:
      in_header: "https://raw.githubusercontent.com/kameronyork/kameronyork.github.io/main/parables/header.html"
      after_body: "https://raw.githubusercontent.com/kameronyork/kameronyork.github.io/main/parables/footer.html"
    code_folding: hide
---

```{r setup, include=FALSE}
library(tidyverse)
library(pander)
library(plotly)
library(DT)
library(latticeExtra)

quotes <- read.csv("https://www.kameronyork.com/datasets/conference-quotes.csv", encoding="UTF-8")
quote_counts <- quotes %>% 
  group_by(scripture) %>% 
  summarise(quote_count = n())
verses <- read.csv("https://www.kameronyork.com/datasets/scripture-verses.csv", encoding="UTF-8") %>% 
  mutate("book_chapter" = paste(book, chapter, sep = " ")) %>% 
  mutate("quoted" = case_when(
    scripture %in% quotes$scripture ~ "Found",
    TRUE ~ ""
  )) %>% 
  left_join(quote_counts, by = c("scripture" = "scripture")) %>% 
  mutate(quote_count = ifelse(is.na(quote_count), 0, quote_count))
verse_order_data <- read.csv("https://www.kameronyork.com/datasets/verse-order.csv", encoding="UTF-8")
verse_order <- strsplit(verse_order_data$order, ", ") %>% 
  unlist()

chapters <- verses %>% 
  group_by(book_chapter) %>% 
  summarise("verses" = n(),
            "book_chapter_order" = min(verse_id))

```

## Overall Quotes Analysis
```{r}
total_by_year <- quotes %>% 
  group_by(talk_year) %>% 
  summarise("total_quotes" = n())

ggplot(data = total_by_year) + 
  geom_area(mapping = aes(x = talk_year, y = total_quotes), fill="steelblue", alpha=0.5) +
  labs(title="Total Quotes by Year",
       x = "Year", 
       y = "Total Scriptures Quoted") +
  theme_bw()
```

```{r}
book_by_year <- quotes %>% 
  group_by(quad_book, talk_year) %>% 
  summarise("total_quotes" = n())

big_book_by_year <- quotes %>% 
  group_by(overall_book, talk_year) %>% 
  summarise("total_quotes" = n())

ggplot(data = book_by_year) + 
  geom_area(mapping = aes(x = talk_year, y = total_quotes, fill = quad_book), position="identity", alpha = 0.5) +
  labs(title="Total Quotes by Book and Year",
       x = "Year", 
       y = "Total Scriptures Quoted per Book") +
  theme_bw()
```

```{r}
ggplot(data = book_by_year) + 
  geom_line(mapping = aes(x = talk_year, y = total_quotes, color = quad_book), size=1) +
  labs(title="Total Quotes by Book and Year",
       x = "Year", 
       y = "Total Scriptures Quoted per Book") +
  theme_bw()
```

```{r}
ggplot(data = big_book_by_year) + 
  geom_line(mapping = aes(x = talk_year, y = total_quotes, color = overall_book), size=1) +
  labs(title="Total Quotes by Book and Year",
       x = "Year", 
       y = "Total Scriptures Quoted per Book") +
  theme_bw()
```

```{r}
ggplot(data = filter(big_book_by_year, overall_book == "Book of Mormon")) + 
  geom_line(mapping = aes(x = talk_year, y = total_quotes, color = overall_book), size=1) +
  geom_smooth(mapping = aes(x = talk_year, y = total_quotes))
  labs(title="Total Quotes by Book and Year",
       x = "Year", 
       y = "Total Scriptures Quoted per Book") +
  theme_bw()

```

### What are the top 10 Scriptures of all time?
```{r}
all_time <- quotes %>% 
  filter(scripture != "null null:null") %>% # Removes the null values from the data.
  group_by(scripture) %>% 
  summarise("count" = n()) %>% 
  arrange(desc(count)) %>% 
  mutate("rank" = rank(desc(count), ties.method = "max")) %>% 
  filter(rank %in% c(1:10))

all_time_10 <- quotes %>% 
  filter(scripture != "null null:null") %>% # Removes the null values from the data.
  group_by(scripture) %>% 
  summarise("count" = n()) %>% 
  arrange(desc(count)) %>% 
  mutate("rank" = rank(desc(count), ties.method = "max")) %>% 
  filter(rank %in% c(1:10)) %>% 
  left_join(y = verses, x = all_time, by = "scripture") %>% 
  select(c("scripture", "count", "rank", "text"))

history_all_time_10 <- quotes %>% 
  filter(scripture %in% all_time_10$scripture) %>% 
  mutate("decade" = paste(str_sub(talk_year, 1, 3), 0, sep="")) %>% 
  group_by(decade)

pander(select(all_time_10, c("scripture", "count", "rank")))
```


```{r}
ggplot(data = history_all_time_10) + 
  geom_bar(mapping = aes(x = decade, fill = scripture), size=1, position="dodge") +
  labs(title="Total Quotes Top 10 Scriptures all Time",
       x = "Year", 
       y = "Total Scriptures Quoted per Book") +
  theme_bw()
```

```{r}
line_all_time_history <- history_all_time_10 %>% 
  group_by(decade = as.numeric(decade), scripture) %>% 
  summarise("count" = n())


ggplot(data = line_all_time_history) + 
  geom_line(mapping = aes(x = decade, y = count, color = scripture), size=1) +
  labs(title="Total Quotes Top 10 Scriptures all Time",
       x = "Year", 
       y = "Total Scriptures Quoted per Book") +
  theme_bw()
```

#### Displaying them over time?



### What about in different decades?



### Creating a Grid:

```{r}
my_plot <- ggplot(data = verses, aes(x = verse, y = fct_rev(factor(book_chapter, levels = verse_order)), fill = quoted)) +
  geom_tile(col = "white") +
  coord_equal(ratio=2.33) +
  scale_fill_manual(values = c("NA" = "white", "Found" = "red")) +
  scale_x_continuous(breaks = unique(verses$verse)) + 
  theme_minimal() +
  theme(
    legend.position = "right",
    panel.background = element_rect(fill = "white"),
    axis.text.y = element_text(size = rel(0.5)),
    axis.text.x = element_blank(),
    axis.title.y = element_blank()
  ) + 
  guides(fill = "none")

ggsave(filename = "C:/Users/theka/Pictures/my_plot.png", plot = my_plot, width = 8, height = 120, units = "in", limitsize = FALSE, bg = "white")

```



```{r}
levels_check <- verses %>%
  select(book_chapter) %>% 
  mutate("check" = case_when(
    book_chapter %in% verse_order ~ "FOUND",
    TRUE ~ "NOT"
  ))


```

<script>
  $(document).ready( function () {
      $('#table_id').DataTable();
  } );
</script>



<div class="dataTables_filter">
  <label>Search Scripture: <input type="search" class="form-control form-control-sm" placeholder="" aria-controls="table_id"></label>
</div>


```{r}
library(DT)

datatable(
  select(filter(quotes, talk_year >= 2000), c("talk_year", "talk_month", "talk_day", "talk_session", "scripture", "speaker")),
  colnames = c("Combined Scripture", "Year", "Month", "Day", "Session ID", "Speaker"),
  options = list(
    searching = TRUE,
    searchCols = list(
      list(targets = 5, search = "applied")
    )
  )
)

```


```{r}
# Remove zero values in quote_count
plot_3d <- verses %>% 
  mutate(quote_count = ifelse(quote_count == 0, NA, quote_count))

# Convert columns to numeric if they are not already
plot_3d$verse <- as.numeric(plot_3d$verse)
plot_3d$quote_count <- as.numeric(plot_3d$quote_count)

fig <- plot_ly(data = plot_3d, x = ~verse, y = ~factor(book_chapter, levels = verse_order), z = ~quote_count) %>% 
  add_markers(size = 5) %>% 
  layout(
    scene = list(
      xaxis = list(title = 'Verse'),
      yaxis = list(title = 'Chapter'),
      zaxis = list(title = 'Quotes'),
      aspectratio = list(x = 1, y = 3, z = 1)
    ),
    xaxis = list(title = 'Overall Book')  # Add x-axis title
  )

fig
```

