---
title: "South Fork Ward - Ministering Assignment Groups"
output:
  html_document:
    includes:
      in_header: "https://www.kameronyork.com/_includes/head-shared.html"
      before_body:
        - "https://www.kameronyork.com/_includes/nav.html"
      after_body: "https://www.kameronyork.com/_includes/footer.html"
header-includes:
  - '<link rel="canonical" href="https://www.kameronyork.com/_drafts/ministering-districts.html">'
  - '<meta property="og:title" content="South Fork Ward - Ministering Assignment Groups">'
  - '<meta property="og:image" content="https://www.kameronyork.com/assets/img/icon.png">'
  - '<meta property="og:url" content="https://www.kameronyork.com/_drafts/ministering-districts.html">'
  - '<meta property="og:type" content="website">'
  - '<meta property="og:site_name" content="Kameron York">'
  - '<meta name="twitter:card" content="summary_large_image">'
  - '<meta name="twitter:title" content="South Fork Ward - Ministering Assignment Groups">'
  - '<meta name="twitter:image" content="https://www.kameronyork.com/assets/img/icon.png">'
---

```{r, include=FALSE, warnings=FALSE}
library(tidyverse)
library(leaflet)
library(tidygeocoder)

households <- read.csv("https://www.kameronyork.com/datasets/southfork-households.csv") %>% 
  geocode(Combined.Address, method = 'arcgis', lat = lat , long = long)
```

```{r, include=FALSE}
red_icon <- makeIcon(
  iconUrl = "https://www.kameronyork.com/assets/img/marker-red.png",
  iconWidth = 25, iconHeight = 25
)

yellow_icon <- makeIcon(
  iconUrl = "https://www.kameronyork.com/assets/img/marker-yellow.png",
  iconWidth = 25, iconHeight = 25)

blue_icon <- makeIcon(
  iconUrl = "https://www.kameronyork.com/assets/img/marker-blue.png",
  iconWidth = 25, iconHeight = 25)
```


### Suggested Map

This map shows the suggested configuration of Districts for Ministering brother assignments:

```{r}
(myleaflet <- leaflet() %>% 
  setView(lng = -111.74, lat = 43.86, zoom = 13) %>% 
  addProviderTiles(providers$OpenStreetMap) %>%
  addMarkers(data = households,
                   lat = ~lat,
                   lng = ~long,
                   popup = ~paste(Name, Assigned, sep = "<br>"),
                   icon = blue_icon))
  # # addMarkers(data = st_as_sf(df_wells),
  # #                  group = "Wells",
  # #                  popup = ~paste("Well:", Owner, sep = " "),
  # #                  icon = dam_icon) %>% 
  # ) %>% 
  # addLayersControl(overlayGroups = c("Wise", "Baker", "Moss"),
  #                  options = layersControlOptions(collapsed = FALSE))
```

